---
DB_NAME: wordpress
DB_USER: wordpress
DB_PASSWORD: wordpress
DB_HOST: 192.168.100.10

nginx:
  my_domains:
      kvitaly.ru:
        #port: 443
        server_name: kvitaly.ru
        #proxy_pass: http://192.168.100.12/

php_modules:
  - php7.4
  - php7.4-fpm
  - php7.4-common
  - php7.4-mysql
  - php7.4-gmp
  - php7.4-curl
  - php7.4-intl
  - php7.4-mbstring
  - php7.4-xmlrpc
  - php7.4-gd
  - php7.4-xml
  - php7.4-cli
  - php7.4-zip