---
domain_name:
  - kvitaly.ru
#  - www.kvitaly.ru
  - gitlab.kvitaly.ru
  - grafana.kvitaly.ru
  - prometheus.kvitaly.ru
  - alertmanager.kvitaly.ru

nginx:
  my_domains:
      kvitaly.ru:
        port: 443
        server_name: kvitaly.ru
        proxy_pass: http://192.168.100.15/
      gitlab.kvitaly.ru:
        port: 443
        server_name: gitlab.kvitaly.ru
        proxy_pass: http://192.168.100.20/
      grafana.kvitaly.ru:
        port: 443
        server_name: grafana.kvitaly.ru
        proxy_pass: http://192.168.100.30/
      prometheus.kvitaly.ru:
        port: 443
        server_name: prometheus.kvitaly.ru
        proxy_pass: http://192.168.100.40/
      alertmanager.kvitaly.ru:
        port: 443
        server_name: alertmanager.kvitaly.ru
        proxy_pass: http://192.168.100.50/

challenge:
  - { num: 0, domain: 'kvitaly.ru' }
  - { num: 1, domain: 'gitlab.kvitaly.ru' }
  - { num: 2, domain: 'grafana.kvitaly.ru' }
  - { num: 3, domain: 'prometheus.kvitaly.ru' }
  - { num: 4, domain: 'alertmanager.kvitaly.ru' }

challenge_www:
  - { num: 0, domain: 'www.kvitaly.ru' }
  - { num: 1, domain: 'www.gitlab.kvitaly.ru' }
  - { num: 2, domain: 'www.grafana.kvitaly.ru' }
  - { num: 3, domain: 'www.prometheus.kvitaly.ru' }
  - { num: 4, domain: 'www.alertmanager.kvitaly.ru' }