---
- name: "Upgrade the OS"
  become: true
  ansible.builtin.shell: "sudo apt-get update"
  args:
    executable: /bin/bash
  tags: [install]

- name: "Install python pip"
  become: true
  ansible.builtin.apt:
    name: python3-pip
  tags: [install]

- name: "Install pymysql"
  become: true
  ansible.builtin.shell: "sudo pip3 install pymysql"
  args:
    executable: /bin/bash
  tags: [install]

- name: "Install mysql-server"
  become: true
  ansible.builtin.apt:
    name: mysql-server
    force_apt_get: yes
  tags: [install]